defaults:
  -
    values:
      author: "Sarah Overmyer"
author: Sarah Overmyer
permalink: /:categories/:month-:day-:year/:title
kramdown:
  input: GFM
exclude: ["package-lock.json", "package.json", "Gemfile", "Gemfile.lock"]